question_data = [{"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "The Republic of Malta is the smallest microstate worldwide.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "History", "type": "boolean", "difficulty": "hard",
                  "question": "The Kingdom of Prussia briefly held land in Estonia.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "medium",
                  "question": "In the game 'Racko' you may pick up ANY card from the discard pile.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Animals", "type": "boolean", "difficulty": "medium",
                  "question": "'Kamea,' the Gilbertese Islander word for dog, is derived from the English "
                              "phrase 'Come here!'",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                  "question": "In 'Portal 2', Cave Johnson started out Aperture Science as a shower curtain company.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
                  "question": "Klingons once had a period of Democracy in their history, they referred to it as the 'Dark Times'.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                  "question": "Nick Mason is the only member to appear on every Pink Floyd album.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
